### PR TITLE
Added support for NetStandard15 and changed to VS2017

### PR DESCRIPTION
**Pull request by snakefoot**
This will build the nuget-package:

`dotnet pack .\src\NLog.Redis --configuration Release --include-symbols`

Have to update appveyor to use VS2017-image.

### CODE REVIEW

**Comment by snakefoot** [comment]
[NLog.Redis.1.0.3.nupkg.zip](https://github.com/richclement/NLog.Redis/files/1913199/NLog.Redis.1.0.3.nupkg.zip) (Remove the zip extension and place in local nuget folder source)

**Comment by 304NotModified** [comment]
bump from https://stackoverflow.com/questions/50162049/is-nlog-redis-supported-on-net-core

**Review by 304NotModified — APPROVED** [review]

**Comment by 304NotModified** [comment]
@richclement   Looks good to me, please update the appveyor config (or move to appveyor.yml, there is an export) and merge it :)

**Comment by 304NotModified** [comment]
polite bump @richclement

**Comment by 304NotModified** [comment]
@gamingrobot I'm not the owner of this Repo. That's @richclement

**Comment by 304NotModified** [comment]
that could be an option, but unfortunately I have no experience with Redis. It makes maintenance hard.

**Comment by Silvenga** [comment]
@304NotModified even if the NLog organization doesn't have the experience to maintain this library directly, I think it would be best for the community if NLog had, at least, contributor access to the Github repo and Nuget packages, for the sole purpose of having a "continuity plan". If the core maintainers fall off the face of the earth for a well used extension, which happens all the time (to no one's fault), the community can still continue. NLog, for example, can delegate different maintainers when needed, reducing the commitments for everyone involved.

I know @gamingrobot and myself could maintain this library if needed. 😸

**Comment by 304NotModified** [comment]
> I know @gamingrobot and myself could maintain this library if needed

Sounds like a good plan!

**Comment by 304NotModified** [comment]
I will try to send @richclement a mail, still prefer owner move instead of fork

**Comment by Silvenga** [comment]
@304NotModified I know @gamingrobot was trying to contact him via LinkedIn (only place we found to contact him at).

**Comment by 304NotModified** [comment]
mail sent (by nuget.org - contact owners)

**Comment by 304NotModified** [comment]
> @304NotModified I know @gamingrobot was trying to contact him via LinkedIn (only place we found to contact him at).

No response via LinkedIn?

**Comment by 304NotModified** [comment]
no response indeed :(

**Comment by 304NotModified** [comment]
I've created a fork and new PR already: https://github.com/NLog/NLog.Redis/pull/1

any idea for the package name in nuget ?

**Comment by Silvenga** [comment]
Maybe NLog.Contrib.Redis? If this is going to be a hard fork, it might be better to just mirror the repository - Github does weird things with forks sometimes.

**Comment by 304NotModified** [comment]
What about NLog.Target.Redis?

> Maybe NLog.Contrib.Redis?

Also not a bad idea, but none of the current packages are "contrib". 

> If this is going to be a hard fork, it might be better to just mirror the repository - Github does weird things with forks sometimes.

I never have problems with forks in git/github. Could you please elaborate on that?

**Comment by Silvenga** [comment]
> I never have problems with forks in git/github. Could you please elaborate on that?

Just an annoyance, a couple of things I've seen:  

- Github likes to treat forks as a pre-pull request - so Github likes to constantly suggest to create a pull request to the root.
- A weird metrics oddity (you can see with https://github.com/Silvenga/btsync-deb or ~Jenkins~), Github won't record commits on your account unless they are merged into the root (I'm assuming to prevent double commits).
- Github tries to be helpful with the UI - autofilling with the root of the fork (sometimes a little annoying): 
image
- Weird things that happen when the main repo is removed by the owner - experienced that with EdiWeave (https://github.com/Silvenga/EdiWeave). A random fork becomes the root.

It actually looks like Jenkins's root repo (https://github.com/jenkinsci/jenkins) was coverted to a root repo - the repo is no longer a fork (it used to be, and it was annoying).

> What about NLog.Target.Redis?

My only worry is that the name is a single character off from `NLog.Targets.Redis`. I can see people mistyping that really easily (especially with the dotnet CLI) and getting confused with what the difference is.

Also, `NLog.Target.Redis` kind of exists too (https://github.com/mattgwagner/NLog.Targets.Redis) - via https://www.nuget.org/packages/renanmt_NLog.Target.Redis/. 

I wonder how hard it would be merging the API for `NLog.Targets.Redis` (https://www.nuget.org/packages/NLog.Targets.Redis) with `NLog.Redis` - then taking over that package. I think @diadistis is the owner of this nuget package.

**Comment by 304NotModified** [comment]
@Silvenga thanks, you convinced me! It's now a unlinked-fork (still here: https://github.com/NLog/NLog.Redis)

Maybe move also discussions over there. Feel free to open a new issue


> I know @gamingrobot and myself could maintain this library if needed. 😸

I will add you :)

**Comment by 304NotModified** [comment]
I guess this one could be closed. ;)

**Comment by snakefoot** [comment]
Closed as merged into: https://github.com/NLog/NLog.Targets.Redis

**Pull request closed without merging**
